### ISSUE TITLE
Can the python version used by ansible-rm be updated to python3

### ISSUE THREAD

**Issue by odaly** [IBM/open-source-service-lifecycle-mgmt#3]
the lmctl tool that comes bundled in ALM CICD Hub, is failing to successfully test the Hello  World Service (sample service contained in GOGS), it seems that ansible-rm is using python2, can we update to to use python3 going forward ?

**Comment by joschkappel** [comment]
ansible-rm uses python3 for local playbooks (those executed inside the ansiblerm container) as well as for playbooks executed on the target host.
